name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up dep
        run: go get github.com/PuerkitoBio/goquery

      - name: Set up depend
        run: go get github.com/go-co-op/gocron

      - name: Build
        run: go build mmrp-scraper/cmd/mmrp
